<dl>
      <dt><a href="list.php?tid=[field:id/]"><img src="/m/skin/images/index_service_2.jpg" alt="[field:typename/]" class="width100" /></a></dt>
      <dd class="t"><a href="list.php?tid=[field:id/]" class="f28"><em class="f28">02</em>商城网站建设</a></dd>
      <dd class="spec"><a href="list.php?tid=[field:id/]" class="f24">专业量身定制策划设计<br>
        拥有资深研发团队</a></dd>
      <dd class="btn"><a href="list.php?tid=[field:id/]"><img src="/m/skin/images/index_btn_service.jpg" alt="点击查看" class="width100" /></a></dd>
    </dl>