<li class="thumbnail" style="display:block;opacity:1;"><a class="thumbnail_a" href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" class="cases_img" alt="[field:title/]"  />
      <div class="projectinfo" style="display: none;"></div>
      </a>
      <div class="meta" >
        <h4 class="fl"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h4>
        <div class="fr"><a href="[field:arcurl/]" target="_blank" class="cases_a_pc"></a><a href="" target="_blank" class="cases_a_phone"></a></div>
        <div class="c"></div>
      </div>
    </li>