<li class="thumbnail" style="display:block;opacity:1;"><a class="thumbnail_a" href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" class="cases_img" width="385" height="250" alt="[field:title/]"  />
      <div class="projectinfo" style="display: none;"></div>
      </a>
      <div class="meta" >
        <h4 class="fl"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h4>
        <div class="fr"><a href="[field:arcurl/]" target="_blank" class="cases_a_pc"></a> 
          <!--手机站演示地址调用开始--> 
          <a href="" target="_blank" class="cases_a_phone"></a> 
          <!--手机站演示地址调用结束--> 
        </div>
        <div class="c"></div>
      </div>
    </li>