<dl class="f">
      <dt><a href="list.php?tid=[field:id/]"><img src="/m/skin/images/index_service_1.jpg" alt="[field:typename/]" class="width100" /></a></dt>
      <dd class="t"><a href="list.php?tid=[field:id/]" class="f28"><em class="f28">01</em>品牌官网设计</a></dd>
      <dd class="spec"><a href="list.php?tid=[field:id/]" class="f24">策划、设计、前端、后台<br>
        设计师一对一沟通</a></dd>
      <dd class="btn"><a href="list.php?tid=[field:id/]"><img src="/m/skin/images/index_btn_service.jpg" alt="点击查看" class="width100" /></a></dd>
    </dl>