<li>
                <div class="solu_img"><a href="[field:arcurl/]" target="_blank" class="shade"></a>
                  <div class="img_icon"><a href="[field:arcurl/]" target="_blank"><img src="/index/skin/img/sl_icon.png" alt="查看[field:title/]详细" width="40" height="40"/></a></div>
                  <img src="[field:picname/]" width="370" height="120" alt="[field:title/]" /></div>
                <h2><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
                <p class="intro"><a href="[field:arcurl/]" target="_blank">[field:description function="cn_substr(@me,160)"/]...</a></p>
              </li>