<dl class="f">
      <dt><a href="list.php?tid=[field:id/]"><img src="/m/skin/images/index_service_3.jpg" alt="[field:typename/]" class="width100" /></a></dt>
      <dd class="t"><a href="list.php?tid=[field:id/]" class="f28"><em class="f28">03</em>手机\微信网站建设</a></dd>
      <dd class="spec"><a href="list.php?tid=[field:id/]" class="f24">个性设计，独一无二<br>
        零成本增加微信网站</a></dd>
      <dd class="btn"><a href="list.php?tid=[field:id/]"><img src="/m/skin/images/index_btn_service.jpg" alt="点击查看" class="width100" /></a></dd>
    </dl>