<dl>
      <dt><a href="list.php?tid=[field:id/]"><img src="/index/m/index/skin/images/index_service_4.jpg" alt="[field:typename/]" class="width100" /></a></dt>
      <dd class="t"><a href="list.php?tid=[field:id/]" class="f28"><em class="f30">04</em>高端网站定制</a></dd>
      <dd class="spec"><a href="list.php?tid=[field:id/]" class="f24">逻辑可行就能帮你实现<br>
        国内最好定制公司</a></dd>
      <dd class="btn"><a href="list.php?tid=[field:id/]"><img src="/index/m/index/skin/images/index_btn_service.jpg" alt="点击查看" class="width100" /></a></dd>
    </dl>