<dl class="dl[field:global.autoindex/]">
      <dt onClick="show_more('1')"><a href="javascript:void(0)" class="f24"><span class="f28">+</span>[field:title/]</a></dt>
      <dt class="t"><a href="view.php?aid=[field:id/]" class="f24"><span class="f28">-</span>[field:title/]</a></dt>
      <dd class="spec"><a href="view.php?aid=[field:id/]" class="f20">[field:description function="cn_substr(@me,100)"/]...</a></dd>
    </dl>