<?php
$z[0]=Array("type"," <a class=\"f30\" href=\"list.php?tid=[field:id/]\">[field:typename/]</a>",72,176);
$z[0][4]['typeid']="13";
$z[1]=Array("type","\r\n        <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n        ",254,386);
$z[1][4]['typeid']="28";
$z[2]=Array("type","\r\n        <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n        ",397,529);
$z[2][4]['typeid']="31";
$z[3]=Array("type","\r\n        <li class=\"last\"><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n        ",540,685);
$z[3][4]['typeid']="36";
$z[4]=Array("type","\r\n        <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n        ",696,828);
$z[4][4]['typeid']="37";
$z[5]=Array("type","\r\n        <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n        ",839,971);
$z[5][4]['typeid']="38";
$z[6]=Array("type"," <a class=\"f30\" href=\"list.php?tid=[field:id/]\">[field:typename/]</a>",1070,1174);
$z[6][4]['typeid']="27";
$z[7]=Array("global","",1386,1410);
$z[7][4]['name']="cfg_dizhi";
$z[8]=Array("global","",1608,1629);
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",1656,1677);
$z[9][4]['name']="cfg_qq";
$z[10]=Array("global","",1872,1896);
$z[10][4]['name']="cfg_email";
$z[11]=Array("global","",2088,2117);
$z[11][4]['name']="cfg_topdianhua";
$z[12]=Array("type"," <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a>",2248,2340);
$z[12][4]['typeid']="29";
$z[13]=Array("global","",2412,2438);
$z[13][4]['name']="cfg_powerby";
$z[14]=Array("global","",2449,2473);
$z[14][4]['name']="cfg_beian";
$z[15]=Array("global","",2648,2677);
$z[15][4]['name']="cfg_topdianhua";
$z[16]=Array("type"," <a href=\"list.php?tid=[field:id/]\"><img id=\"menu_3\" src=\"/m/skin/images/nav_3.jpg\" class=\"width100\" alt=\"[field:typename/]\" /></a>",2785,2950);
$z[16][4]['typeid']="6";
$z[17]=Array("type"," <a href=\"list.php?tid=[field:id/]\"><img id=\"menu_4\" src=\"/m/skin/images/nav_4.jpg\" class=\"width100\" alt=\"[field:typename/]\" /></a>",2966,3132);
$z[17][4]['typeid']="16";

?>