<?php
$z[0]=Array("global","",129,155);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",264,290);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",420,449);
$z[2][4]['name']="cfg_topdianhua";
$z[3]=Array("global","",486,510);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",557,583);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",654,680);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",761,848);
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("channel","\r\n          <li class=\"\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",894,1129);
$z[7][4]['type']="top";
$z[7][4]['currentstyle']="<li class='on'><a href='~typelink~' ~rel~>~typename~</a></li>";

?>