<?php
$z[0]=Array("channel","\r\n    <li><a href=\"list.php?tid=[field:id/]\" class=\"f28\">[field:typename/]\r\n      <div><img src=\"/index/m/index/skin/images/ico_menu_jiantou.png\" alt=\"[field:typename/]\" class=\"width100\" /></div>\r\n      </a></li>\r\n    ",204,687);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li><a href='list.php?tid=~id~' ~rel~ class='f28'><span>~typename~ <div><img src='/index/m/index/skin/images/ico_menu_jiantou.png' alt='[field:typename/]' class='width100' /></div> </span></a> </li>";

?>