<?php
$z[0]=Array("field","",207,226);
$z[0][4]['name']="title";
$z[1]=Array("global","",227,253);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",701,730);
$z[2][4]['name']="typename";
$z[3]=Array("global","",795,821);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",1009,1048);
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n      ",1142,1410);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='sel'><a href='list.php?tid=~id~' ~rel~ class='f24'><span>~typename~</span></a></li>";
$z[6]=Array("type","\r\n      <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n      ",1424,1551);
$z[6][4]['typeid']="3";
$z[7]=Array("type","\r\n      <li><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n      ",1560,1687);
$z[7][4]['typeid']="4";
$z[8]=Array("type","\r\n      <li class=\"last\"><a href=\"list.php?tid=[field:id/]\" class=\"f24\">[field:typename/]</a></li>\r\n      ",1696,1836);
$z[8][4]['typeid']="5";
$z[9]=Array("field","",1892,1913);
$z[9][4]['name']="content";
$z[10]=Array("include","",1934,1973);
$z[10][4]['filename']="footer_m.htm";

?>