<?php
$z[0]=Array("field","",260,279);
$z[0][4]['name']="title";
$z[1]=Array("global","",280,306);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",347,376);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",416,474);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",953,988);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n              <li>\r\n                <div class=\"solu_img\"><a href=\"[field:arcurl/]\" target=\"_blank\" class=\"shade\"></a>\r\n                  <div class=\"img_icon\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"/skin/img/sl_icon.png\" alt=\"查看[field:title/]详细\" width=\"40\" height=\"40\"/></a></div>\r\n                  <img src=\"[field:picname/]\" width=\"370\" height=\"120\" alt=\"[field:title/]\" /></div>\r\n                <h2><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\r\n                <p class=\"intro\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:description function=\"cn_substr(@me,160)\"/]...</a></p>\r\n              </li>\r\n             ",1396,2101);
$z[5][4]['pagesize']="18";
$z[6]=Array("include","",2177,2214);
$z[6][4]['filename']="footer.htm";
$z[7]=Array("include","",2224,2260);
$z[7][4]['filename']="right.htm";

?>