<?php
$z[0]=Array("field","",230,249);
$z[0][4]['name']="title";
$z[1]=Array("global","",250,276);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",317,346);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",386,444);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",865,900);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","\r\n  <div class=\"case_t_title\">[field:typename /]</div>\r\n  ",1281,1363);
$z[6]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n    ",1468,1669);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='sel'><a href='~typelink~'>~typename~</a> </li>";
$z[7]=Array("list","\r\n    <li class=\"thumbnail\" style=\"display:block;opacity:1;\"><a class=\"thumbnail_a\" href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:picname/]\" class=\"cases_img\" width=\"385\" height=\"250\" alt=\"[field:title/]\"  />\r\n      <div class=\"projectinfo\" style=\"display: none;\"></div>\r\n      </a>\r\n      <div class=\"meta\" >\r\n        <h4 class=\"fl\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h4>\r\n        <div class=\"fr\"><a href=\"[field:arcurl/]\" target=\"_blank\" class=\"cases_a_pc\"></a> \r\n          <!--手机站演示地址调用开始--> \r\n          <a href=\"\" target=\"_blank\" class=\"cases_a_phone\"></a> \r\n          <!--手机站演示地址调用结束--> \r\n        </div>\r\n        <div class=\"c\"></div>\r\n      </div>\r\n    </li>\r\n    ",2212,3002);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",3098,3145);
$z[8][4]['listitem']="pageno";
$z[8][4]['listsize']="2";
$z[9]=Array("include","",3211,3248);
$z[9][4]['filename']="footer.htm";
$z[10]=Array("include","",3258,3294);
$z[10][4]['filename']="right.htm";

?>